-- vim.cmd.colorscheme "monokai"
-- vim.cmd.colorscheme "moonfly"
-- vim.cmd.colorscheme "sonokai"
-- vim.cmd.colorscheme "monokai_pro"
-- vim.cmd.colorscheme "srcery"
-- vim.cmd.colorscheme "PaperColor"
-- vim.cmd.colorscheme "jellybeans"
-- vim.cmd([[
--   let g:gruvbox_italic=1
--   let g:gruvbox_contrast_dark='hard'
-- ]])
-- vim.cmd.colorscheme "gruvbox"
-- vim.cmd.colorscheme "badwolf"
-- vim.cmd.colorscheme "hybrid"
-- vim.cmd.colorscheme "tokyonight-night"
-- vim.cmd.colorscheme "gruvbox-material"
-- vim.cmd.colorscheme "codedark"
-- vim.cmd.colorscheme "catppuccin-mocha"
-- vim.cmd.colorscheme "neon"
-- vim.cmd.colorscheme "ayu"

-- require('kanagawa').setup({
--   colors = {
--     palette = {
--       -- change all usages of these colors
--       sumiInk0 = "#000000",
--       fujiWhite = "#FFFFFF",
--     },
--     theme = {
--       -- change specific usages for a certain theme, or for all of them
--       wave = {
--         ui = {
--           diff = {
--             delete = "#00FF00",
--           },
--         },
--       },
--     }
--   },
-- })
vim.cmd.colorscheme "kanagawa"


