require("plugins")
require("core.options")
require("core.keymaps")
require("core.colorscheme")
require("plugins.autopairs")
require("plugins.git-blame")
require("plugins.harpoon")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.nvim-cmp")
require("plugins.nvim-dap")
-- require("plugins.nvim-lint")
require("plugins.vim-rest-console")
require("plugins.lsp.mason")
require("plugins.lsp.lspzero")
